### ISSUE TITLE
suggestion for positioning

### ISSUE THREAD

**Issue by El4a** [chrisdavies/tlite#1]
Not a real issue just a remark:

wouldn't it be more logical to have grave:'n' default to above the element? As in to the north of the element? I find it illogical that s is up, n is down, e is right and w is left.

Love your lib btw! =)

**Comment by chrisdavies** [comment]
Hi El4a, thanks! I kinda agree. It was confusing to me at first, too. I based this library off of a jQuery one that was already in one of my codebases, so I followed the pattern of that library.

After I thought about it for a bit, I realized that the n, s, etc is indicating the position of the tooltip arrow, not necessarily the tooltip itself! Crazy, eh?
