### ISSUE TITLE
chrome indicator notches shift 1px at end of css-opacity transtion

### ISSUE THREAD

**Issue by jedierikb** [chrisdavies/tlite#10]
It is an occasional glitch

Details for fix here:
http://stackoverflow.com/questions/14729492/css3-transform-rotate-causing-1px-shift-in-chrome

Was able to fix by prevent by adding:
```
.tlite {
  ...
  -webkit-backface-visibility: hidden;
}

**Comment by chrisdavies** [comment]
Hey, cool. I updated the CSS accordingly. We've been using tlite in production for quite a while, and haven't found any of the issues you've found! Thanks for vetting it so thoroughly.
