### ISSUE TITLE
understanding window clipping

### ISSUE THREAD

**Issue by jedierikb** [chrisdavies/tlite#11]
Your example tooltip wraps nicely when it encounters the edges of the window:
![screen shot 2016-11-04 at 2 11 15 pm](https://cloud.githubusercontent.com/assets/374586/20017131/a6b93fba-a298-11e6-9aab-3811d247c869.png)

This trivial example does not:
![screen shot 2016-11-04 at 2 11 33 pm](https://cloud.githubusercontent.com/assets/374586/20017130/a6af2c6e-a298-11e6-8d9f-a2e271bb5526.png)

(and here is the example: http://codepen.io/jedierikb/pen/mOdzjY?editors=0010)
```
tlite(function (el) { return el.classList.contains('foo'); });

document.body.innerHTML = '<button class="foo" title="I am a long tooltip but i get clipped :-(">Hover Here</button>';
```

How to use your tool to ensure tooltips are not clipped by the window?

**Comment by chrisdavies** [comment]
Yeah. Right now the tool doesn't do anything smart about it. It just puts the tooltip where you tell it. What we do in our app is we place tooltips intelligently based on where components are going to be showing. So, components on the right side of the screen generally are displayed with one of the `east` orientations, and elements on the left side of the screen with one of the `west` orientations.

It should be possible to add a new orientation: `auto` which would be intelligent about this, based on the parent's position and the size of the tooltip. I'm open to a pull request. :)

Also, we tend to only have really small tooltips (one or two words), so this generally isn't an issue.

**Comment by jedierikb** [comment]
I am happy to try my hand at `auto`, but I do not yet understand how your tooltip in the screenshot from your home page knows to word-wrap instead of clip.

http://codepen.io/jedierikb/pen/NbWeXE

**Comment by jedierikb** [comment]
I see.  On your example page you've omitted this line from your css:
https://github.com/chrisdavies/tlite/blob/master/tlite.css#L15

Mystery solved :-P

**Comment by chrisdavies** [comment]
Ah! I hadn't realized that. It may be serving up an old version of the CSS.
