### ISSUE TITLE
Doenst seem to work in a table cell

### ISSUE THREAD

**Issue by El4a** [chrisdavies/tlite#2]
Okay, this time an actual issue =)

It seems that if I use the library with the test example and I add a table cell with a tooltip, for example 

```
  <table>
    <tr>
      <td class="tooltip-n" title="test the tooltip">Tooltip will appear on the wrong place</td>
    </tr>
  </table>
```

the tooltip appears on the wrong position (usually somewhere top left).

**Comment by El4a** [comment]
Nevermind! Someone fixed it for me :) I'll just add 
`table tr td{position:relative;}`

to the styling.  Is it okay if I commit this on the git?

**Comment by chrisdavies** [comment]
Yeah. It's true. It's a tradeoff I made because the only alternative I could think of was to use fixed positioning and manually calculate where to put it. That causes complications on resize, flow changes, etc, so it's "by design", for better or worse. :/

**Comment by El4a** [comment]
Okay I see, however, I think I have a solution that requires little extra and still doesn't ruin the other features. Would you be okay with a pull request to check it out and see if you like it?
