### ISSUE TITLE
Mobile device touch compatibility

### ISSUE THREAD

**Issue by Serveurperso** [chrisdavies/tlite#22]
Hello,

It need a small modification to keep as "manual" for touch screen.
It must work on hover for PC and on touch for mobile device.

Thanks

**Comment by Serveurperso** [comment]
I discovered your pure CSS version and it Rocks !!!
it refresh content and work with any device:D Thanks a lot.

**Comment by chrisdavies** [comment]
Cool. I'm closing this, then! Glad the other project was helpful to you!

**Comment by Serveurperso** [comment]
Yes but I think it's important for this one to get mobile friendly.
