### ISSUE TITLE
Feature request: auto "grav"

### ISSUE THREAD

**Issue by subversivo58** [chrisdavies/tlite#4]
Hi! 
Thanks for this beautiful code :)

My sugest is: auto detect of element position "grav" like this...

     // this is actual method
     var grav = opts.grav || 'n';

     // I sugest this: use data- attribute
     var grav = opts.grav || el.getAttribute('data-tlite') || 'n';

This method allow configure multiple positions

**Comment by chrisdavies** [comment]
Yeah.  I think this is a good idea. It allows the presentation layer to be the place where the position is declared.

I also just realized there are pretty much no tests for this library. Gonna have to work on that.

**Comment by chrisdavies** [comment]
Regarding tests, I just remembered that it's my policy on this one to just make the changes in gh-pages, and make sure the resulting `index.html` still behaves as expected.

**Comment by subversivo58** [comment]
Hum...
I do not quite understand your last comment ... sorry my english is bad :(

I saw now that I have not updated the minification. I'll fix this.

Thanks for listening

**Comment by chrisdavies** [comment]
No problem. I've already updated the minification and published. Thanks for the contribution!
