### ISSUE TITLE
tooltip for disabled button

### ISSUE THREAD

**Issue by jedierikb** [chrisdavies/tlite#7]
```
tlite(function (el) { return el.classList.contains('foo'); });
document.body.innerHTML = '<button class="foo" title="Hi">Hover Here</button>';
document.querySelector( 'button' ).disabled = true;
```
http://codepen.io/jedierikb/pen/vXowXw?editors=0010

Results in an un-stylized tooltip showing up.
I was hoping no tooltip would show up.
What would be the best practice for preventing tooltips on a disabled button?

**Comment by chrisdavies** [comment]
Change this line: 

```javascript
return el.classList.contains('foo');
```

To be this:

```javascript
return el.classList.contains('foo') && el.disabled === false;
```

**Comment by jedierikb** [comment]
Hmm, still getting an unstylized tooltip.  Take a look:
http://codepen.io/jedierikb/pen/rWBYJb?editors=0011

Related: it seems that disabled on a button causes the classlist check for 'foo' to report false negatives?

**Comment by chrisdavies** [comment]
Ah. I see what you're saying. It's not an unstyled tooltip, actually. That has nothing to do with `tlite`. It's the browser's handling of the button's "title" attribute, and since disabled buttons don't fire 'mouseover' events, tlite doesn't hook into the button... Hm...

Here's a workaround for now:

http://output.jsbin.com/paruce/1

Pretty hacky, though. Basically, you put the tooltip on a wrapper (span in this case), and style the wrapper with a bit of padding (otherwise, some browsers don't fire an onmouseover for the span).

**Comment by jedierikb** [comment]
Why not use a different attribute, something other than 'title'?

**Comment by chrisdavies** [comment]
Well, the idea was to have a reasonable fallback, so if tlite fails, you still get tooltips via the browser's default handling of title. But yeah. We could add an option, maybe falling back to `data-title` if there is no title attribute.

What do you think?

**Comment by El4a** [comment]
Is there also an easy option to _do_ show the tooltip on a disabled button?

**Comment by mgrubinger** [comment]
It seems `mouseover` are not fired for `[disabled]` elements (see [https://jakearchibald.com/2017/events-and-disabled-form-fields/](https://jakearchibald.com/2017/events-and-disabled-form-fields/)

I'm experimenting with replacing `mouseover` with `pointerover` and `mouseleave` with `pointerleave` events, but these seem to be not supported by Safari :/ 
(see [https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/pointerover_event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/pointerover_event))

Which leaves us with either 
1) wrapping the disabled button with a <div> or something to trigger the tooltip
2) or feature detect pointer-events and use pointer-events when supported or mouseevents when not (which again, tooltips on disabled elements would still not work in safari)

Bummer. I guess I'll just go for option 1 and wrap the button.

**Comment by El4a** [comment]
Nevermind, Ive found out it's standard browser behaviour to not fire mouseevents on disabled elements. Stupid. Element wrapping it is then

**Comment by El4a** [comment]
Ha wow okay that was synchronously :D thx :)
