### ISSUE TITLE
switching tooltip text on click events shows browser default title

### ISSUE THREAD

**Issue by jedierikb** [chrisdavies/tlite#9]
https://www.youtube.com/watch?v=gLo1zjf7D6Q
http://codepen.io/jedierikb/pen/xRxGNQ?editors=0011

```
var tip1 = true;
tlite(function (el) { 
  return el.classList.contains('foo');
});
document.body.innerHTML = '<button class="foo" title="tip1">Hover Here</button>';

var $b = document.querySelector('button');
$b.addEventListener( 'click', function() {
  tip1 = !tip1;
  tlite.hide( $b );
  $b.setAttribute( 'title', tip1 ? 'tip1' : 'tip2' );
  // tlite.show( $b );
});
```

**Comment by chrisdavies** [comment]
Based on your other feedback, I added a `data-tlite` fallback.

If you don't use title, but instead add a `data-tlite="Hello World!"` attribute to your elements, the browser should only show tlite messages. That should fix this issue, too.
